name: Deploy GTC Staking Contract to BSC Testnet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Deploy Contract
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          BSC_RPC: "https://data-seed-prebsc-1-s1.binance.org:8545/"
        run: |
          npx hardhat run scripts/deploy.js --network bsctestnet
